/* Datos del objeto Usuario */

export interface User{
    id?: number,
    name?: string,
    surname1?: string,
    surname2?: string,
    representativeName?: string,
    email: string,
    password?:string,
    password_confirmation?:string,
    api_token?:string,
    avatar:string,
    givenName?: string,
    user_type_id?:any,
    hide_my_user?:any,
    price?:number,
    gender?:any,
    proffesion?: string,
    birthdate?:Date,
    description?:string,
    user_labels?:any,
    user_type_categories?:any,
    actuallocation?:any,
    mylabels?:any,
    completedTask?:any,
    allmylabels?:any,
    allmycategories?:any,
    user_verified?:any,
    hasRequest?:any,
    hasFollow?:any,
    hasChat?:any,
    notificationsPermissions?:any,
    translateUserLabels?:any,
    allmypronouns?:any,
    averageRating?:any,
    countRatings?:any,
    hasTrialMonth?:any,
    sub_id?:any,
    hasWaiting?:any
    
}